spring:
  datasource:
    url: jdbc:mysql://39.107.125.189:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Li1289794166
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 8
    min-idle: 1
    max-active: 20
    max-wait: 60000
    time-between-eviction-runsMillis: 60000
    min-evictable-idle-timeMillis: 300000
    validation-query: select 'x' FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    filters: stat,wall
    max-pool-prepared-statement-per-connection-size: 20
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    use-global-data-source-stat: true

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.gis_server.pojo

auth-server: http://localhost:8080
#
#security:
#  oauth2:
#    client:
#      client-id: c1
#      client-secret: secret
#      user-authorization-uri: ${auth-server}/oauth/authorize
#      access-token-uri: ${auth-server}/oauth/token
#    resource:
##      id: CHAT
#      jwt:
##        key-uri: ${auth-server}/oauth/token_key
#        key-value: uaa123
